---
- name: Check MDW JDK versions
  hosts: all
  gather_facts: false

  roles:
    - check_jdk_rpm

  post_tasks:

    - name: Build final JDK upgrade summary
      ansible.builtin.set_fact:
        jdk_upgrade_summary: >-
          {%- set result = [] -%}
          {%- for host in ansible_play_hosts -%}
            {%- if hostvars[host].mdw_jdk_outdated | default([]) | length > 0 -%}
              {%- set jdks = [] -%}
              {%- for jdk in hostvars[host].mdw_jdk_outdated -%}
                {%- set _ = jdks.append(
                  jdk.package
                  ~ ' [installed='
                  ~ jdk.installed
                  ~ ', required='
                  ~ jdk.required
                  ~ ']'
                ) -%}
              {%- endfor -%}
              {%- set _ = result.append(
                host ~ ' requires upgrade: ' ~ (jdks | join(', '))
              ) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ result }}
      run_once: true

    - name: FINAL JDK UPGRADE SUMMARY
      ansible.builtin.debug:
        var: jdk_upgrade_summary
      run_once: true