```bash
post_tasks:
  - name: Build MDW JDK outdated summary
    ansible.builtin.set_fact:
      jdk_summary: >-
        {%- set result = [] -%}
        {%- for host in ansible_play_hosts -%}
          {%- if hostvars[host].mdw_jdk_needs_update | default(false) -%}
            {%- for jdk in hostvars[host].mdw_jdk_outdated -%}
              {%- set _ = result.append(
                host ~ ' | '
                ~ jdk.package ~ ' | '
                ~ jdk.installed ~ ' -> '
                ~ jdk.required
              ) -%}
            {%- endfor -%}
          {%- endif -%}
        {%- endfor -%}
        {{ result }}
    run_once: true

  - name: MDW JDK OUTDATED HOSTS
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ jdk_summary }}"
    loop_control:
      label: ""
    run_once: true
```