apiVersion: argoproj.io/v1alpha1
kind: Workflow

metadata:
  generateName: openshift-poc-tomcat-

spec:
  entrypoint: build-tomcat

  arguments:
    parameters:

      - name: docker-repo
        value: docker.artifactory.cib.echonet

      - name: artifactory
        value: middleware-docker-local-dev.artifactory.cib.echonet

      - name: git-repo
        value: bitbucket.cib.echonet:7999/middleware/kube-cicd.git

      - name: git-revision
        value: feature/openshift-poc

      - name: image-name
        value: openshift-poc-tomcat

      - name: image-tag
        value: 10.1.57-jdk11-debian13


  templates:

    - name: build-tomcat

      metadata:
        annotations:

          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "VAULT_ROLE_OPENSHIFT"

          vault.hashicorp.com/secret-volume-path-idrsa: "/ssh"
          vault.hashicorp.com/agent-inject-secret-idrsa: "secret/ssh"

          vault.hashicorp.com/agent-inject-template-idrsa: |
            {{- with secret "RUTA_VAULT_SSH" -}}
            {{ .Data.data.private }}
            {{- end }}

          vault.hashicorp.com/secret-volume-path-config-json: "/secrets"
          vault.hashicorp.com/agent-inject-secret-config-json: "secret/buildkit-configjson"

          vault.hashicorp.com/agent-inject-template-config-json: |
            {{- with secret "RUTA_VAULT_DOCKER" -}}
            {{ .Data.data | toUnescapedJSON }}
            {{- end }}


      volumes:
        - name: workspace
          emptyDir: {}


      initContainers:

        - name: git-clone

          image: "{{workflow.parameters.docker-repo}}/alpine/git"

          command:
            - /bin/sh
            - -ec

          args:
            - |
              echo "=========================================="
              echo "Clonando repositorio"
              echo "Branch: {{workflow.parameters.git-revision}}"
              echo "=========================================="

              mkdir -p /tmp/ssh

              cp /ssh/idrsa /tmp/ssh/id_rsa
              chmod 600 /tmp/ssh/id_rsa

              export GIT_SSH_COMMAND="ssh \
                -i /tmp/ssh/id_rsa \
                -o StrictHostKeyChecking=no \
                -o UserKnownHostsFile=/dev/null"

              git clone \
                --branch "{{workflow.parameters.git-revision}}" \
                --single-branch \
                "ssh://git@{{workflow.parameters.git-repo}}" \
                /workspace/repository

              echo
              echo "Repositorio clonado."

              echo
              echo "Comprobando Dockerfile:"

              ls -la \
                /workspace/repository/openshift-poc/tomcat

              test -f \
                /workspace/repository/openshift-poc/tomcat/Dockerfile

              echo
              echo "Dockerfile encontrado."

          volumeMounts:

            - name: workspace
              mountPath: /workspace


      container:
        name: buildkit

        image: "{{workflow.parameters.docker-repo}}/moby/buildkit:v0.9.3-rootless"

        workingDir: /workspace/repository/openshift-poc/tomcat

        env:

          - name: DOCKER_CONFIG
            value: /secrets

        command:
          - buildctl-daemonless.sh

        args:

          - build

          - --frontend
          - dockerfile.v0

          - --local
          - context=.

          - --local
          - dockerfile=.

          - --output
          - >-
            type=image,name={{workflow.parameters.artifactory}}/{{workflow.parameters.image-name}}:{{workflow.parameters.image-tag}},push=true


        volumeMounts:

          - name: workspace
            mountPath: /workspace


        securityContext:
          allowPrivilegeEscalation: false

          capabilities:
            drop:
              - ALL